### ISSUE TITLE
"trying to install a new helper tool"

### ISSUE THREAD

**Issue by azdesertfather** [dustinrue/ControlPlane#452]
A box continues to pop up on the screen as long as ControlPlane is running that says "ControlPlane is trying to install a new helper tool. Type your password to allow this."  It then has a box to type in Username & Password, and buttons below saying "Cancel" and "Install Helper."  No matter what I try, however, the box keeps popping back up.  Re-installing hasn't helped.
![screen shot 2016-07-21 at 10 18 41 am](https://cloud.githubusercontent.com/assets/20580655/17026315/adb225c0-4f2d-11e6-9814-28dc45cab338.jpg)

**Comment by azdesertfather** [comment]
Another note:  after it asks me a couple of times to put this information in, it then says "Error: Failed to install privileged helper: (null)".

![screen shot 2016-07-21 at 11 42 23 am](https://cloud.githubusercontent.com/assets/20580655/17029182/40a29518-4f38-11e6-9b9a-f70aa4885926.jpg)

**Comment by dustinrue** [comment]
Best thing to do is to download the source and run the remove_helper_tool.sh script with sudo

sudo ./remove_helper_tool.sh

And then allow ControlPlane to try it again from scratch.

**Comment by azdesertfather** [comment]
Thanks dustinrue.  What do you mean by "download the source"?  I looked in the package contents for the app and didn't see anything in there called "remove_helper_tool.sh".  Also, what do you mean by "run...with sudo"?  I'm assuming you're talking about typing a command in Terminal, but I'm not well versed on how to type in and run such things efficiently.

**Comment by christopherdwhite** [comment]
@azdesertfather, did you ever get this figured out? I Believe Dustin is recommending the following:

1. Go the **Code** tab for this GitHub repo
2. Select **Clone or Download**
3. Select **Download ZIP**
4. Unzip the file in your Downloads folder.
5. Open the **Terminal** (it's in the Utilities folder in Applications)
6. Enter `cd ~/Downloads/ControlPlane-master/Utilities/`and press enter.
7. Enter `sudo ./remove_helper_tool.sh` and press enter.
8. Enter your admin password and you should be all good.

If that spits out an error make sure you downloaded the app from the following URL and try again: http://www.controlplaneapp.com/download/CI

@dustinrue I just ran into the same problem and running the remove_helper_tool.sh didn't work because helper file wasn't being created in the first place. I had installed it via Homebrew Cask and it looks like it was using a specific version of ControlPlane instead of grabbing the latest from the above URL. 

Here's the [Cask](https://github.com/caskroom/homebrew-cask/blob/c023b005d66d4cdcb3a714f7f803833bdd86eff1/Casks/controlplane.rb):

```ruby
cask 'controlplane' do
  if MacOS.version <= :snow_leopard
    version '1.2.3'
    sha256 '37f93d3a3a17a6e2f24447f0bc74c7e89ec1581ca52e5970960544858c86f909'
  else
    version '1.6.4'
    sha256 '5050f48212390aa7fd4d22677db3a5e1b14db1289ddef52867748a3e1a841ed5'

    appcast 'http://www.controlplaneapp.com/appcast.xml',
            checkpoint: 'c9b44eb0ea2d2c7dd1cde14d60fd00a7cf8b4b6bc5b7b5b75cc4ec836b43aed3'
  end

  url "http://www.controlplaneapp.com/download/#{version}"
  name 'ControlPlane'
  homepage 'http://www.controlplaneapp.com/'
  license :gpl

  depends_on macos: '>= :snow_leopard'

  app 'ControlPlane.app'

  zap delete: '~/Library/Preferences/com.dustinrue.ControlPlane.plist'
end
```

Once I downloaded the correct version everything went fine.

I've added update the cask to my 'to-cask' list but I'm not sure when I'll get around to it so I thought I'd let you know it needs updating too.

**Comment by dustinrue** [comment]
What the cask provides is the latest official release. The CI version is based off of the most recent build.

**Comment by christopherdwhite** [comment]
Oh, got it, I misunderstood. Thanks for the clarification! And for keeping such a great tool alive.

**Comment by dustinrue** [comment]
Latest update should resolve the issue. Get it from ControlPlane's check for updates menu item.

**Comment by benshell** [comment]
For anyone else struggling with this issue, the latest update did not resolve the problem for me, however downloading the repo and running the `remove_helper_tool.sh` script as described above did fix it.
